---

- name: Take out Trash
  file:
    path: '$PWD/../../generated_configs/{{ inventory_hostname }}.txt'
    state: absent
  delegate_to: localhost


- name: Create New Configs
  ansible.builtin.template:
    src: 'nxos.j2'
    dest: '$PWD/../../generated_configs/{{ inventory_hostname }}.txt'
    lstrip_blocks:  yes
  delegate_to: localhost
